package by.training.task4.controller.command;

public enum CommandType {
    EXIT, CREATECOUNTRY, OPENCOUNTRY,SAVECOUNTRY,
    ADDCITY,ADDDISTRICT,ADDREGION,
    CHANGECITY,CHANGEDISTRICT,CHANGEREGION,CHANGECOUNTRY,
    GETINFOUNIT
}
