-- MySQL Script generated by MySQL Workbench
-- Tue Nov  2 21:32:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema beauty_parlor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beauty_parlor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`user` ;

CREATE TABLE IF NOT EXISTS `test`.`user` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `login` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
    `password` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
    `name` VARCHAR(128) CHARACTER SET 'utf8mb4' NOT NULL,
    `role` ENUM('client', 'employee', 'admin') CHARACTER SET 'utf8mb4' NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `e-mail_UNIQUE` (`login` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`category` ;

CREATE TABLE IF NOT EXISTS `test`.`category` (
                                                          `id` INT NOT NULL,
                                                          `name` VARCHAR(100) NOT NULL,
    `description` VARCHAR(2000) CHARACTER SET 'utf8mb4' NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
    ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table `test`.`procedure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`procedure` ;

CREATE TABLE IF NOT EXISTS `test`.`procedure` (
                                                           `id` INT NOT NULL AUTO_INCREMENT,
                                                           `category_id` INT NOT NULL,
                                                           `name` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
    `description` VARCHAR(2000) CHARACTER SET 'utf8mb4' NOT NULL,
    `elapsed_time` TINYINT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
    INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
    CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `test`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`procedure_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`procedure_employee` ;

CREATE TABLE IF NOT EXISTS `test`.`procedure_employee` (
                                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                                    `employee_id` INT NOT NULL,
                                                                    `procedure_id` INT NOT NULL,
                                                                    `price` DECIMAL(2) NOT NULL,
    `rating` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `procedure_id_idx` (`procedure_id` ASC) VISIBLE,
    INDEX `emplyee_id_idx` (`employee_id` ASC) VISIBLE,
    CONSTRAINT `procedure_id`
    FOREIGN KEY (`procedure_id`)
    REFERENCES `test`.`procedure` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `emplyee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`appointment` ;

CREATE TABLE IF NOT EXISTS `test`.`appointment` (
                                                             `id` INT NOT NULL AUTO_INCREMENT,
                                                             `user_id` INT NOT NULL,
                                                             `procedure_employee_id` INT NOT NULL,
                                                             `date` DATETIME NOT NULL,
                                                             `status` TINYINT NOT NULL DEFAULT 0,
                                                             `price` DECIMAL(2) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `service_id_idx` (`procedure_employee_id` ASC) VISIBLE,
    INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `procedure_emplyee_id`
    FOREIGN KEY (`procedure_employee_id`)
    REFERENCES `test`.`procedure_employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `beauty_parlor`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`score` ;

CREATE TABLE IF NOT EXISTS `test`.`score` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `user_id` INT NOT NULL,
                                                       `value` TINYINT NOT NULL,
                                                       `appointment_id` INT NOT NULL,
                                                       `comment` TEXT(200) CHARACTER SET 'utf8mb4' NULL,
    `date` DATE NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `appointment`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `test`.`appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;